<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <EmitDialectRuntimeManifest>true</EmitDialectRuntimeManifest>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\UniversalToolchain.Capabilities.Abstractions\UniversalToolchain.Capabilities.Abstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Abstractions\UniversalToolchain.Dialects.Abstractions.csproj"/>
        <ProjectReference Include="..\AssemblyFinder\AssemblyFinder.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\VariablesRuntime\VariablesRuntime.csproj"/>
        <ProjectReference Include="..\EqualityModule\EqualityModule.csproj"/>
        <ProjectReference Include="..\InternalPreprocessorLexemesModule\InternalPreprocessorLexemesModule.csproj"/>
        <ProjectReference Include="..\IdentifierModule\IdentifierModule.csproj"/>
        <ProjectReference Include="..\ScopesModule\ScopesModule.csproj"/>
        <ProjectReference Include="..\SettableGettableModule\SettableGettableModule.csproj"/>
        <ProjectReference Include="..\UniversalIntermediateRepresentation\UniversalIntermediateRepresentation.csproj"/>
        <ProjectReference Include="..\ExceptionsManager\ExceptionsManager.csproj"/>
<ProjectReference Include="..\UniversalToolchain.ModuleContracts\UniversalToolchain.ModuleContracts.csproj"/>
    </ItemGroup>

</Project>
