<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../BasicCore/BasicCore.csproj"/>
        <ProjectReference Include="../../Shared/BasicTypesExtensions/BasicTypesExtensions.csproj"/>
        <ProjectReference Include="../../Shared/ExceptionsManager/ExceptionsManager.csproj"/>
        <ProjectReference Include="../../Shared/ListExtensions/ListExtensions.csproj"/>
        <ProjectReference Include="../../Shared/CommonExceptions/CommonExceptions.csproj"/>
    </ItemGroup>

</Project>
