<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\DotnetHelper\DotnetHelper.csproj"/>
        <ProjectReference Include="..\ExceptionsManager\ExceptionsManager.csproj"/>
        <ProjectReference Include="..\IntermediateRepresentationAbstractions\IntermediateRepresentationAbstractions.csproj"/>
        <ProjectReference Include="..\ListExtensions\ListExtensions.csproj"/>
        <ProjectReference Include="..\ObjectExtensions\ObjectExtensions.csproj"/>
    </ItemGroup>

</Project>
