<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>bin</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>bin</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ArithmeticModule\ArithmeticModule.csproj"/>
        <ProjectReference Include="..\BasicCilCompiler\BasicCilCompiler.csproj"/>
        <ProjectReference Include="..\BasicCodeTranslator\BasicCodeTranslator.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\BasicInterpreter\BasicInterpreter.csproj"/>
        <ProjectReference Include="..\BasicLexer\BasicLexer.csproj"/>
        <ProjectReference Include="..\BasicParser\BasicParser.csproj"/>
        <ProjectReference Include="..\BasicTypesExtensions\BasicTypesExtensions.csproj"/>
        <ProjectReference Include="..\BytecodeDynamicMethodsCompiler\BytecodeDynamicMethodsCompiler.csproj"/>
        <ProjectReference Include="..\ConditionsModule\ConditionsModule.csproj"/>
        <ProjectReference Include="..\CSharpInteropModule\CSharpInteropModule.csproj"/>
        <ProjectReference Include="..\ExecutorLoggerModule\ExecutorLoggerModule.csproj"/>
        <ProjectReference Include="..\IdentifierModule\IdentifierModule.csproj"/>
        <ProjectReference Include="..\LabelsModule\LabelsModule.csproj"/>
        <ProjectReference Include="..\NumbersModule\NumbersModule.csproj"/>
        <ProjectReference Include="..\ParserConfigurationModule\ParserConfigurationModule.csproj"/>
        <ProjectReference Include="..\ScopesModule\ScopesModule.csproj"/>
        <ProjectReference Include="..\SemicolonAsNewLineModule\SemicolonAsNewLineModule.csproj"/>
        <ProjectReference Include="..\VariablesModule\VariablesModule.csproj"/>
        <ProjectReference Include="..\WhitespacesModule\WhitespacesModule.csproj"/>
    </ItemGroup>

</Project>
