<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <BuildInParallel>false</BuildInParallel>
    <RestoreBuildInParallel>false</RestoreBuildInParallel>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\UniversalToolchain\UniversalToolchain.LanguageAuthoring\UniversalToolchain.LanguageAuthoring.csproj" />
    <ProjectReference Include="..\..\UniversalToolchain\UniversalToolchain.LanguageSdk\UniversalToolchain.LanguageSdk.csproj" />
    <ProjectReference Include="..\..\UniversalToolchain\UniversalToolchain.Runtime\UniversalToolchain.Runtime.csproj" />
  </ItemGroup>
</Project>
