<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GrEmit" Version="3.5.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Shared/ExceptionsManager/ExceptionsManager.csproj"/>
        <ProjectReference Include="../../IR/IntermediateRepresentationAbstractions/IntermediateRepresentationAbstractions.csproj"/>
        <ProjectReference Include="../../IR/UniversalIntermediateRepresentation/UniversalIntermediateRepresentation.csproj"/>
    </ItemGroup>

</Project>
