global using CommonExceptions;
global using AbstractIrExtensions;
global using AssemblyFinder;
global using BasicCore.Attributes;
global using BasicCore.Contracts;
global using BasicCore.LexerWrapper;
global using BasicCore.ParserWrapper;
global using BasicCore.TranslatorWrapper;
global using BasicTypesExtensions;
global using CSharpInteropModule.Creators;
global using CSharpInteropModule.Visitors;
global using DynamicMethodWrapper;
global using ExceptionsManager;
global using LexemeType = BasicTypesExtensions.ExtensibleEnum<BasicCore.LexerWrapper.LexemeTag>;
