<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <EmitDialectRuntimeManifest>true</EmitDialectRuntimeManifest>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\UniversalToolchain.Capabilities.Abstractions\UniversalToolchain.Capabilities.Abstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Abstractions\UniversalToolchain.Dialects.Abstractions.csproj"/>
        <ProjectReference Include="..\AbstractIrExtensions\AbstractIrExtensions.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\BasicTypesExtensions\BasicTypesExtensions.csproj"/>
        <ProjectReference Include="..\ObjectExtensions\ObjectExtensions.csproj"/>
        <ProjectReference Include="..\UniversalIntermediateRepresentation\UniversalIntermediateRepresentation.csproj"/>
        <ProjectReference Include="..\ExceptionsManager\ExceptionsManager.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Diagnostics.Abstractions\UniversalToolchain.Diagnostics.Abstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Rules.Abstractions\UniversalToolchain.Rules.Abstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Integration\UniversalToolchain.Dialects.Integration.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Optimizers\"/>
    </ItemGroup>

</Project>
