<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AbstractIrExtensions\AbstractIrExtensions.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\BasicTypesExtensions\BasicTypesExtensions.csproj"/>
        <ProjectReference Include="..\DotnetAirHelper\DotnetAirHelper.csproj"/>
        <ProjectReference Include="..\ObjectExtensions\ObjectExtensions.csproj"/>
        <ProjectReference Include="..\UniversalIntermediateRepresentation\UniversalIntermediateRepresentation.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Optimizers\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
    </ItemGroup>

</Project>
