<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ILDisassembler" Version="1.0.1"/>
        <PackageReference Include="Mono.Reflection" Version="2.0.0"/>
    </ItemGroup>

</Project>
