<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExceptionsManager\ExceptionsManager.csproj"/>
        <ProjectReference Include="..\AbstractIrConverters\AbstractIrConverters.csproj"/>
        <ProjectReference Include="..\BasicCodeTranslator\BasicCodeTranslator.csproj"/>
        <ProjectReference Include="..\BasicCilCompiler\BasicCilCompiler.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\BasicInterpreter\BasicInterpreter.csproj"/>
        <ProjectReference Include="..\BasicLexer\BasicLexer.csproj"/>
        <ProjectReference Include="..\BasicParser\BasicParser.csproj"/>
        <ProjectReference Include="..\BytecodeDynamicMethodsCompiler\BytecodeDynamicMethodsCompiler.csproj"/>
        <ProjectReference Include="..\DynamicMethodWrapper\DynamicMethodWrapper.csproj"/>
        <ProjectReference Include="..\IntermediateRepresentationAbstractions\IntermediateRepresentationAbstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Abstractions\UniversalToolchain.Dialects.Abstractions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Parsing\UniversalToolchain.Dialects.Parsing.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Frontend\UniversalToolchain.Dialects.Frontend.csproj"/>
    </ItemGroup>

</Project>
