<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExceptionsManager\ExceptionsManager.csproj"/>
        <ProjectReference Include="..\ObjectExtensions\ObjectExtensions.csproj"/>
    </ItemGroup>

</Project>
