global using System.Reflection;
global using System.Reflection.Emit;
global using System.Runtime.CompilerServices;
global using ExceptionsManager;
global using ObjectExtensions;
global using System.Collections.Concurrent;
global using BasicCore.Compilation;
global using BasicCore.Execution;
global using DynamicMethodCalling.Core;
