<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ArithmeticModule\ArithmeticModule.csproj"/>
        <ProjectReference Include="..\BasicCodeTranslator\BasicCodeTranslator.csproj"/>
        <ProjectReference Include="..\BasicCore\BasicCore.csproj"/>
        <ProjectReference Include="..\BasicInterpreter\BasicInterpreter.csproj"/>
        <ProjectReference Include="..\BasicStdLib\BasicStdLib.csproj"/>
        <ProjectReference Include="..\BytecodeDynamicMethodsCompiler\BytecodeDynamicMethodsCompiler.csproj"/>
        <ProjectReference Include="..\AbstractIrConverters\AbstractIrConverters.csproj"/>
        <ProjectReference Include="..\ConditionsModule\ConditionsModule.csproj"/>
        <ProjectReference Include="..\CSharpInteropModule\CSharpInteropModule.csproj"/>
        <ProjectReference Include="..\ExecutorLoggerModule\ExecutorLoggerModule.csproj"/>
        <ProjectReference Include="..\IdentifierModule\IdentifierModule.csproj"/>
        <ProjectReference Include="..\LabelsModule\LabelsModule.csproj"/>
        <ProjectReference Include="..\LoopsModule\LoopsModule.csproj"/>
        <ProjectReference Include="..\NativeMathModule\NativeMathModule.csproj"/>
        <ProjectReference Include="..\LocalVariablesOptimizerModule\LocalVariablesOptimizerModule.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Integration\UniversalToolchain.Dialects.Integration.csproj"/>
        <ProjectReference Include="..\NumbersModule\NumbersModule.csproj"/>
        <ProjectReference Include="..\ParserConfigurationModule\ParserConfigurationModule.csproj"/>
        <ProjectReference Include="..\ScopesModule\ScopesModule.csproj"/>
        <ProjectReference Include="..\SemicolonAsNewLineModule\SemicolonAsNewLineModule.csproj"/>
        <ProjectReference Include="..\VariablesModule\VariablesModule.csproj"/>
        <ProjectReference Include="..\WhitespacesModule\WhitespacesModule.csproj"/>
        <ProjectReference Include="..\CommonExceptions\CommonExceptions.csproj"/>
        <ProjectReference Include="..\UniversalToolchain.Dialects.Wist\UniversalToolchain.Dialects.Wist.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Dialects\examples\wist\**\dialect.wistdialect">
            <Link>Dialects\examples\wist\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
