<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Frontend/BasicCore/BasicCore.csproj"/>
        <ProjectReference Include="../../Frontend/BasicLexer/BasicLexer.csproj"/>
        <ProjectReference Include="../../Frontend/BasicParser/BasicParser.csproj"/>
        <ProjectReference Include="../../Frontend/BasicCodeTranslator/BasicCodeTranslator.csproj"/>
        <ProjectReference Include="../../IR/AbstractIrConverters/AbstractIrConverters.csproj"/>
        <ProjectReference Include="../../Shared/ExceptionsManager/ExceptionsManager.csproj"/>
        <ProjectReference Include="../../Shared/CommonExceptions/CommonExceptions.csproj"/>
        <ProjectReference Include="../UniversalToolchain.Dialects.Abstractions/UniversalToolchain.Dialects.Abstractions.csproj"/>
    </ItemGroup>

</Project>
