<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="UniversalToolchain.LanguageAuthoring" Version="0.3.0-alpha.4" />
    <PackageReference Include="UniversalToolchain.LanguageSdk" Version="0.3.0-alpha.4" />
    <PackageReference Include="UniversalToolchain.Runtime" Version="0.3.0-alpha.4" />
  </ItemGroup>
</Project>
